// Code generated by protoc-gen-go.
// source: Common.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	Common.proto
	FightBefore.proto
	FightingAfter.proto
	Fighting.proto
	Oauth.proto

It has these top-level messages:
	CommonResponse
	InitRoomMsg
	PlayerJionMsg
	UserInput
	UserInputData
	CollectUsersInput
	UserLogin
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonResponse struct {
	State int32 `protobuf:"varint,1,opt,name=state" json:"state,omitempty"`
}

func (m *CommonResponse) Reset()                    { *m = CommonResponse{} }
func (m *CommonResponse) String() string            { return proto.CompactTextString(m) }
func (*CommonResponse) ProtoMessage()               {}
func (*CommonResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*CommonResponse)(nil), "pb.CommonResponse")
}

func init() { proto.RegisterFile("Common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x71, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe3, 0xe2,
	0x83, 0x88, 0x05, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x89, 0x70, 0xb1, 0x16, 0x97,
	0x24, 0x96, 0xa4, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x41, 0x38, 0x4e, 0x1c, 0xab, 0x98,
	0x58, 0x03, 0x40, 0xba, 0x92, 0xd8, 0xc0, 0x9a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8e,
	0xd8, 0x90, 0x73, 0x4c, 0x00, 0x00, 0x00,
}
